pub const KIWI_BUILD_INTEGRATE_ALLOMORPH: i32 = 1;
pub const KIWI_BUILD_LOAD_DEFAULT_DICT: i32 = 2;
pub const KIWI_BUILD_LOAD_TYPO_DICT: i32 = 4;
pub const KIWI_BUILD_LOAD_MULTI_DICT: i32 = 8;
pub const KIWI_BUILD_DEFAULT: i32 = 15;
pub const KIWI_BUILD_MODEL_TYPE_DEFAULT: i32 = 0x0000;
pub const KIWI_BUILD_MODEL_TYPE_LARGEST: i32 = 0x0100;
pub const KIWI_BUILD_MODEL_TYPE_KNLM: i32 = 0x0200;
pub const KIWI_BUILD_MODEL_TYPE_SBG: i32 = 0x0300;
pub const KIWI_BUILD_MODEL_TYPE_CONG: i32 = 0x0400;
pub const KIWI_BUILD_MODEL_TYPE_CONG_GLOBAL: i32 = 0x0500;
pub const KIWI_BUILD_DEFAULT_WITH_CONG: i32 = KIWI_BUILD_DEFAULT | KIWI_BUILD_MODEL_TYPE_CONG;
pub const KIWI_NUM_THREADS: i32 = 0x8001;

pub const KIWI_TYPO_WITHOUT_TYPO: i32 = 0;
pub const KIWI_TYPO_BASIC_TYPO_SET: i32 = 1;
pub const KIWI_TYPO_CONTINUAL_TYPO_SET: i32 = 2;
pub const KIWI_TYPO_BASIC_TYPO_SET_WITH_CONTINUAL: i32 = 3;
pub const KIWI_TYPO_LENGTHENING_TYPO_SET: i32 = 4;
pub const KIWI_TYPO_BASIC_TYPO_SET_WITH_CONTINUAL_AND_LENGTHENING: i32 = 5;

pub const KIWI_MATCH_URL: i32 = 1;
pub const KIWI_MATCH_EMAIL: i32 = 2;
pub const KIWI_MATCH_HASHTAG: i32 = 4;
pub const KIWI_MATCH_MENTION: i32 = 8;
pub const KIWI_MATCH_SERIAL: i32 = 16;
pub const KIWI_MATCH_NORMALIZE_CODA: i32 = 1 << 16;
pub const KIWI_MATCH_JOIN_NOUN_PREFIX: i32 = 1 << 17;
pub const KIWI_MATCH_JOIN_NOUN_SUFFIX: i32 = 1 << 18;
pub const KIWI_MATCH_JOIN_VERB_SUFFIX: i32 = 1 << 19;
pub const KIWI_MATCH_JOIN_ADJ_SUFFIX: i32 = 1 << 20;
pub const KIWI_MATCH_JOIN_ADV_SUFFIX: i32 = 1 << 21;
pub const KIWI_MATCH_JOIN_V_SUFFIX: i32 = KIWI_MATCH_JOIN_VERB_SUFFIX | KIWI_MATCH_JOIN_ADJ_SUFFIX;
pub const KIWI_MATCH_JOIN_AFFIX: i32 = KIWI_MATCH_JOIN_NOUN_PREFIX
    | KIWI_MATCH_JOIN_NOUN_SUFFIX
    | KIWI_MATCH_JOIN_V_SUFFIX
    | KIWI_MATCH_JOIN_ADV_SUFFIX;
pub const KIWI_MATCH_SPLIT_COMPLEX: i32 = 1 << 22;
pub const KIWI_MATCH_Z_CODA: i32 = 1 << 23;
pub const KIWI_MATCH_COMPATIBLE_JAMO: i32 = 1 << 24;
pub const KIWI_MATCH_SPLIT_SAISIOT: i32 = 1 << 25;
pub const KIWI_MATCH_MERGE_SAISIOT: i32 = 1 << 26;

pub const KIWI_MATCH_ALL: i32 = KIWI_MATCH_URL
    | KIWI_MATCH_EMAIL
    | KIWI_MATCH_HASHTAG
    | KIWI_MATCH_MENTION
    | KIWI_MATCH_SERIAL
    | KIWI_MATCH_Z_CODA;
pub const KIWI_MATCH_ALL_WITH_NORMALIZING: i32 = KIWI_MATCH_ALL | KIWI_MATCH_NORMALIZE_CODA;

pub const KIWI_DIALECT_STANDARD: i32 = 0;
pub const KIWI_DIALECT_GYEONGGI: i32 = 1 << 0;
pub const KIWI_DIALECT_CHUNGCHEONG: i32 = 1 << 1;
pub const KIWI_DIALECT_GANGWON: i32 = 1 << 2;
pub const KIWI_DIALECT_GYEONGSANG: i32 = 1 << 3;
pub const KIWI_DIALECT_JEOLLA: i32 = 1 << 4;
pub const KIWI_DIALECT_JEJU: i32 = 1 << 5;
pub const KIWI_DIALECT_HWANGHAE: i32 = 1 << 6;
pub const KIWI_DIALECT_HAMGYEONG: i32 = 1 << 7;
pub const KIWI_DIALECT_PYEONGAN: i32 = 1 << 8;
pub const KIWI_DIALECT_ARCHAIC: i32 = 1 << 9;
pub const KIWI_DIALECT_ALL: i32 = (1 << 10) - 1;

pub(crate) const KIWI_RELEASES_API_BASE: &str =
    "https://api.github.com/repos/bab2min/Kiwi/releases";
